In [2]:
# -*- coding: utf-8 -*-

In [3]:
import random
import pandas as pd
import numpy as np
import numpy.random as nr
from numpy import *

In [4]:
#データセット①
x1 = 10 #
y1 = 20 #データ幅の指定
zz = 3000 #出力データ個数(固定)
r1 = 2 #出力データの小数点指定(整数は０)

In [5]:
#出力モデル
a = np.random.uniform(x1, y1, zz)
a = np.round(a, r1)
a

array([ 13.63,  18.01,  16.74, ...,  15.46,  18.99,  19.17])

In [6]:
#データセット②
x2 = 0.005
y2 = 0.1 #データ幅の指定
r2 = 4 #出力データの小数点指定(整数は０)

In [7]:
b = np.random.uniform(x2, y2, zz)
b = np.round(b, r2)
b

array([ 0.0469,  0.0806,  0.0845, ...,  0.0967,  0.0552,  0.0608])

In [8]:
#データセット③
x3 = 1000
y3 = 2000 #データ幅の指定
r3 = 3 #出力データの小数点指定(整数は０)

In [9]:
c = np.random.uniform(x3, y3, zz)
c = np.round(c, r3)
c

array([ 1136.261,  1472.107,  1559.838, ...,  1891.635,  1649.45 ,
        1586.166])

In [10]:
#データセット④
x4 = 0
y4 = 1 #データ幅の指定
r4 = 0 #出力データの小数点指定(整数は０)

In [11]:
d = np.random.uniform(x4, y4, zz)
d = np.round(d, r4)
d

array([ 1.,  1.,  0., ...,  1.,  1.,  1.])

In [12]:
#時間設定
#開始時間,freqで時間幅を設定
#リファレンス http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases
dt = pd.date_range('2014-11-01 10:00', periods=zz, freq='2H30T17S')
dt

DatetimeIndex(['2014-11-01 10:00:00', '2014-11-01 12:30:17',
               '2014-11-01 15:00:34', '2014-11-01 17:30:51',
               '2014-11-01 20:01:08', '2014-11-01 22:31:25',
               '2014-11-02 01:01:42', '2014-11-02 03:31:59',
               '2014-11-02 06:02:16', '2014-11-02 08:32:33',
               ...
               '2015-09-09 11:07:10', '2015-09-09 13:37:27',
               '2015-09-09 16:07:44', '2015-09-09 18:38:01',
               '2015-09-09 21:08:18', '2015-09-09 23:38:35',
               '2015-09-10 02:08:52', '2015-09-10 04:39:09',
               '2015-09-10 07:09:26', '2015-09-10 09:39:43'],
              dtype='datetime64[ns]', length=3000, freq='9017S')

In [13]:
#データセット⑤
wl = np.array(["パン","牛乳","お肉","お水","砂糖","お茶","野菜","菓子","果物","お米"])
wd = random.choice(wl, zz)
wd

array(['お米', '牛乳', '野菜', ..., 'お茶', '野菜', 'お米'],
      dtype='<U2')

In [14]:
#index
index = np.arange(0,zz,1)
index

array([   0,    1,    2, ..., 2997, 2998, 2999])

In [17]:
#それぞれを統合
#各カラムの名前を設定
df = pd.DataFrame(
{'文字列' : wd,
 '時間' : dt,
 'センサー１' : a,
 'センサー２' : b,
 'センサー３' : c,
 'センサー４' : d})
df

センサー１   センサー２     センサー３  センサー４ 文字列                  時間
0     13.63  0.0469  1136.261    1.0  お米 2014-11-01 10:00:00
1     18.01  0.0806  1472.107    1.0  牛乳 2014-11-01 12:30:17
2     16.74  0.0845  1559.838    0.0  野菜 2014-11-01 15:00:34
3     11.87  0.0109  1298.285    1.0  お肉 2014-11-01 17:30:51
4     15.61  0.0541  1744.595    1.0  お茶 2014-11-01 20:01:08
5     10.33  0.0846  1110.478    1.0  牛乳 2014-11-01 22:31:25
6     18.38  0.0151  1983.919    1.0  お水 2014-11-02 01:01:42
7     12.20  0.0595  1378.972    1.0  菓子 2014-11-02 03:31:59
8     13.18  0.0495  1963.738    0.0  砂糖 2014-11-02 06:02:16
9     10.79  0.0697  1046.634    1.0  菓子 2014-11-02 08:32:33
10    16.67  0.0064  1442.316    0.0  お茶 2014-11-02 11:02:50
11    12.56  0.0228  1590.023    0.0  果物 2014-11-02 13:33:07
12    10.43  0.0358  1981.143    1.0  お米 2014-11-02 16:03:24
13    19.80  0.0383  1643.339    0.0  菓子 2014-11-02 18:33:41
14    10.01  0.0700  1216.265    1.0  お米 2014-11-02 21:03:58
15    17.21  0.0784  1481.400    1.0  お肉 2014-11-02 23:34:15
16    16.48  0.0593  1690.208    0.0  砂糖 2014-11-03 02:04:32
17    14.59  0.0607  1388.911    0.0  砂糖 2014-11-03 04:34:49
18    13.66  0.0915  1988.828    1.0  果物 2014-11-03 07:05:06
19    19.81  0.0850  1578.204    0.0  野菜 2014-11-03 09:35:23
20    16.58  0.0486  1847.775    1.0  牛乳 2014-11-03 12:05:40
21    10.44  0.0999  1777.527    0.0  お肉 2014-11-03 14:35:57
22    14.76  0.0944  1090.764    0.0  砂糖 2014-11-03 17:06:14
23    11.15  0.0607  1403.512    0.0  お米 2014-11-03 19:36:31
24    11.06  0.0993  1652.044    0.0  牛乳 2014-11-03 22:06:48
25    12.62  0.0181  1863.812    1.0  果物 2014-11-04 00:37:05
26    14.43  0.0690  1740.522    1.0  砂糖 2014-11-04 03:07:22
27    16.67  0.0158  1676.531    0.0  お水 2014-11-04 05:37:39
28    12.74  0.0611  1429.505    1.0  菓子 2014-11-04 08:07:56
29    15.72  0.0344  1281.657    1.0  砂糖 2014-11-04 10:38:13
...     ...     ...       ...    ...  ..                 ...
2970  19.73  0.0698  1736.640    1.0  お肉 2015-09-07 09:01:30
2971  16.57  0.0601  1947.526    0.0  お茶 2015-09-07 11:31:47
2972  10.77  0.0284  1644.315    0.0  野菜 2015-09-07 14:02:04
2973  11.63  0.0154  1454.102    0.0  お茶 2015-09-07 16:32:21
2974  19.25  0.0540  1519.149    0.0  パン 2015-09-07 19:02:38
2975  13.29  0.0682  1054.020    0.0  お肉 2015-09-07 21:32:55
2976  17.49  0.0307  1253.333    1.0  パン 2015-09-08 00:03:12
2977  14.05  0.0608  1893.248    0.0  お肉 2015-09-08 02:33:29
2978  18.30  0.0106  1278.837    1.0  牛乳 2015-09-08 05:03:46
2979  10.05  0.0180  1066.340    1.0  お米 2015-09-08 07:34:03
2980  10.22  0.0503  1102.904    0.0  お茶 2015-09-08 10:04:20
2981  19.50  0.0839  1788.493    0.0  牛乳 2015-09-08 12:34:37
2982  17.08  0.0862  1750.914    1.0  パン 2015-09-08 15:04:54
2983  18.77  0.0141  1360.078    0.0  お肉 2015-09-08 17:35:11
2984  14.27  0.0595  1821.174    1.0  お米 2015-09-08 20:05:28
2985  17.68  0.0195  1649.396    1.0  果物 2015-09-08 22:35:45
2986  16.61  0.0656  1694.172    1.0  お肉 2015-09-09 01:06:02
2987  10.75  0.0843  1994.272    0.0  パン 2015-09-09 03:36:19
2988  19.95  0.0612  1450.014    0.0  菓子 2015-09-09 06:06:36
2989  11.09  0.0470  1494.774    1.0  お水 2015-09-09 08:36:53
2990  11.88  0.0069  1322.151    0.0  果物 2015-09-09 11:07:10
2991  12.40  0.0141  1497.192    1.0  野菜 2015-09-09 13:37:27
2992  11.07  0.0828  1229.277    1.0  果物 2015-09-09 16:07:44
2993  19.42  0.0783  1645.112    1.0  パン 2015-09-09 18:38:01
2994  16.11  0.0174  1685.729    1.0  パン 2015-09-09 21:08:18
2995  13.33  0.0927  1106.073    1.0  砂糖 2015-09-09 23:38:35
2996  10.15  0.0711  1144.057    0.0  菓子 2015-09-10 02:08:52
2997  15.46  0.0967  1891.635    1.0  お茶 2015-09-10 04:39:09
2998  18.99  0.0552  1649.450    1.0  野菜 2015-09-10 07:09:26
2999  19.17  0.0608  1586.166    1.0  お米 2015-09-10 09:39:43

[3000 rows x 6 columns]

In [16]:
#CSVで出力
df.to_csv('output.csv', index=False)