In [47]:
# -*- coding: utf-8 -*-
#すべてのセルをSHIFT+Enterで実行します

In [48]:
#ここはとりあえずSHIFT+ENTERでスキップ
import random
import pandas as pd
import numpy as np
import numpy.random as nr
from numpy import *

In [49]:
#サンプル数定義：作成するデータの件数を定義します
dataCount = 3000

In [50]:
#データセットサンプル：ランダムな整数
#最小値
x1 = 500 
#最大値
y1 = 1000 
#出力データの小数点指定(整数は０)
r1 = 0 
#列を作成
a = np.random.uniform(x1, y1, dataCount)
a = np.round(a, r1)
a

array([ 778.,  563.,  678., ...,  694.,  788.,  610.])

In [51]:
#データセットサンプル;文字列
#作成させたい単語リストを配列形式で作成
wl = np.array(["パン","牛乳","お肉","お水","砂糖","お茶","野菜","菓子","果物","お米"])
#列を作成
wd = random.choice(wl, dataCount)
wd

array(['お水', 'お茶', 'お米', ..., '砂糖', 'お肉', '菓子'],
      dtype='<U2')

In [52]:
#データセットサンプル：ランダムな時間データ
#開始時間,freqで時間幅を設定
#リファレンス http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases
dt = pd.date_range('2014-11-01 10:00', periods=dataCount, freq='2H30T17S')
dt

DatetimeIndex(['2014-11-01 10:00:00', '2014-11-01 12:30:17',
               '2014-11-01 15:00:34', '2014-11-01 17:30:51',
               '2014-11-01 20:01:08', '2014-11-01 22:31:25',
               '2014-11-02 01:01:42', '2014-11-02 03:31:59',
               '2014-11-02 06:02:16', '2014-11-02 08:32:33',
               ...
               '2015-09-09 11:07:10', '2015-09-09 13:37:27',
               '2015-09-09 16:07:44', '2015-09-09 18:38:01',
               '2015-09-09 21:08:18', '2015-09-09 23:38:35',
               '2015-09-10 02:08:52', '2015-09-10 04:39:09',
               '2015-09-10 07:09:26', '2015-09-10 09:39:43'],
              dtype='datetime64[ns]', length=3000, freq='9017S')

In [53]:
#データセットサンプル：INDEXデータ
#０から１ずつ足していく
index = np.arange(0,dataCount,1)
index

array([   0,    1,    2, ..., 2997, 2998, 2999])

In [54]:
#ESC+Aでセルを追加できるのでここから以下でデータを定義

In [61]:
#データセットサンプル：ランダムな整数
#最小値
x1 = 10
#最大値
y1 = 20
#出力データの小数点指定(整数は０)
r1 = 0 
#列を作成
b = np.random.uniform(x1, y1, dataCount)
b = np.round(b, r1)
b

array([ 18.,  12.,  13., ...,  10.,  10.,  19.])

In [62]:
#ここまででデータを作成

In [63]:
#最後に列を統合してCSV化する
#各カラムの名前を設定　'列名' : wd(列の変数名),でつないでいく
df = pd.DataFrame(
{'品物' : wd,
 '値段' : a,
 '販売数' : b})

In [64]:
df

値段  品物   販売数
0     778.0  お水  18.0
1     563.0  お茶  12.0
2     678.0  お米  13.0
3     909.0  お水  14.0
4     774.0  牛乳  13.0
5     746.0  お茶  18.0
6     545.0  お肉  11.0
7     622.0  パン  16.0
8     774.0  お米  19.0
9     691.0  菓子  18.0
10    814.0  牛乳  14.0
11    852.0  お米  18.0
12    844.0  果物  10.0
13    590.0  お肉  12.0
14    832.0  お茶  19.0
15    616.0  菓子  18.0
16    754.0  野菜  19.0
17    829.0  パン  14.0
18    846.0  パン  19.0
19    807.0  菓子  19.0
20    690.0  お米  16.0
21    612.0  お米  20.0
22    745.0  お水  17.0
23    601.0  お米  18.0
24    702.0  お肉  13.0
25    666.0  お水  10.0
26    703.0  果物  13.0
27    781.0  パン  17.0
28    758.0  お茶  15.0
29    709.0  パン  13.0
...     ...  ..   ...
2970  836.0  菓子  10.0
2971  520.0  パン  10.0
2972  934.0  お水  13.0
2973  941.0  野菜  13.0
2974  695.0  果物  14.0
2975  693.0  菓子  11.0
2976  796.0  野菜  10.0
2977  883.0  砂糖  12.0
2978  931.0  牛乳  14.0
2979  916.0  果物  11.0
2980  617.0  菓子  11.0
2981  952.0  野菜  13.0
2982  744.0  パン  11.0
2983  530.0  菓子  14.0
2984  745.0  お肉  13.0
2985  889.0  お水  12.0
2986  768.0  砂糖  19.0
2987  701.0  お水  13.0
2988  579.0  お米  19.0
2989  565.0  砂糖  16.0
2990  692.0  菓子  15.0
2991  819.0  お茶  10.0
2992  853.0  お米  15.0
2993  545.0  お米  11.0
2994  547.0  お肉  16.0
2995  562.0  お米  15.0
2996  814.0  野菜  10.0
2997  694.0  砂糖  10.0
2998  788.0  お肉  10.0
2999  610.0  菓子  19.0

[3000 rows x 3 columns]

In [65]:
#CSVで出力
df.to_csv('output.csv', index=False)